
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/php?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root  #自己的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
